version: 2

defaults: &defaults
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/project
    environment:
      TF_IN_AUTOMATION: true

tf-install: &tf-install
  run:
    name: tf-install
    command: |
      wget https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      sudo unzip terraform_0.12.28_linux_amd64.zip -d /usr/bin
      rm terraform_0.12.28_linux_amd64.zip
      terraform --version

jobs:
  terraform-init:
    <<: *defaults
    steps:
      - checkout
      - *tf-install
      - run:
          name: init
          command: terraform init -input=false
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  terraform-plan:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - *tf-install
      - run:
         name: plan
         command: terraform plan -out=plan.tfplan -input=false
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
orbs:
  aws-cli: circleci/aws-cli@1.2.1

workflows:
   version: 2
   install-and-check-env:
     jobs:
        - terraform-init:
           filters:
             branches:
               only: master
        - terraform-plan:
                  requires:
                    - terraform-init